[package]
name = "autovirt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.30"
dotenv-parser = "0.1.3"
lazy_static = "1.4.0"
mexprp = { version = "0.3.1", default-features = false }
nekosbest = "0.20.1"
poise = "0.5.5"
rand = "0.8.5"
sqlx = { version = "0.7.1", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1.32.0", features = ["full"] }
